#!/bin/sh
#~/.i3/i3exit

lock() {
    i3lock -i  $HOME/.i3/lock.png
}

case "$1" in
    lock)
        lock
        ;;
    logout)
        i3-msg exit
        ;;
    suspend)
        lock; systemctl suspend
        ;;
    hibernate)
        lock; systemctl hibernate
        ;;
    reboot)
        systemctl reboot
        ;;
    shutdown)
        systemctl poweroff
        ;;
        *)
esac

exit 0
